name: Platform Builds

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  # Linux x86_64 (native)
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add x86_64-unknown-linux-gnu
      - run: cargo build --release --target x86_64-unknown-linux-gnu
      - uses: actions/upload-artifact@v4
        with:
          name: linux-x86_64
          path: target/x86_64-unknown-linux-gnu/release/

  # Linux i686 (cross)
  linux-i686:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo install cross
      - run: cross build --release --target i686-unknown-linux-gnu
      - uses: actions/upload-artifact@v4
        with:
          name: linux-i686
          path: target/i686-unknown-linux-gnu/release/

  # Linux aarch64 (cross)
  linux-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo install cross
      - run: cross build --release --target aarch64-unknown-linux-gnu
      - uses: actions/upload-artifact@v4
        with:
          name: linux-aarch64
          path: target/aarch64-unknown-linux-gnu/release/

  # Windows x86_64 (native)
  windows-x86_64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add x86_64-pc-windows-gnu
      - run: cargo build --release --target x86_64-pc-windows-gnu
      - uses: actions/upload-artifact@v4
        with:
          name: windows-x86_64
          path: target/x86_64-pc-windows-gnu/release/

  # Windows i686 (cross)
  windows-i686:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo install cross
      - run: cross build --release --target i686-pc-windows-gnu
      - uses: actions/upload-artifact@v4
        with:
          name: windows-i686
          path: target/i686-pc-windows-gnu/release/

  # Windows aarch64 (zigbuild)
windows-aarch64:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: Install Zig and cargo-zigbuild
      run: |
        cargo install cargo-zigbuild
        rustup target add aarch64-pc-windows-msvc
    - name: Build
      run: cargo zigbuild --release --target aarch64-pc-windows-msvc
    - uses: actions/upload-artifact@v4
      with:
        name: windows-aarch64
        path: target/aarch64-pc-windows-msvc/release/


  # macOS x86_64 (native)
  macos-x86_64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add x86_64-apple-darwin
      - run: cargo build --release --target x86_64-apple-darwin
      - uses: actions/upload-artifact@v4
        with:
          name: macos-x86_64
          path: target/x86_64-apple-darwin/release/

  # macOS ARM64 (native)
  macos-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add aarch64-apple-darwin
      - run: cargo build --release --target aarch64-apple-darwin
      - uses: actions/upload-artifact@v4
        with:
          name: macos-arm64
          path: target/aarch64-apple-darwin/release/
